name: PR Title Lint

on:
  pull_request:
    branches: [ "main" ]

permissions:
  content: write
  pull-requests: write
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        id: set-result
        with:
          script: |
            console.log(context)
            pr_title = context.payload.pull_request.title
            if( !pr_title.startsWith("feat: ") && !pr_title.startsWith("fix: ") ){
              core.setFailed("PR title must start with `feat: ` ot `fix: `");
            }
